import JSZip from "jszip";
import { ComponentNode, GenerationResult } from "@/types";

export async function exportToZip(result: GenerationResult) {
    const zip = new JSZip();
    const componentsFolder = zip.folder("components");
    const typesFolder = zip.folder("types");

    const components: ComponentNode[] = [];
    const collectComponents = (node: ComponentNode) => {
        components.push(node);
        if (node.children) {
            node.children.forEach(collectComponents);
        }
    };
    collectComponents(result.tree);

    // Add components
    components.forEach((node) => {
        if (componentsFolder) {
            componentsFolder.file(`${node.name}.tsx`, node.code);
        }
    });

    // Add types (Hardcoded from types/index.ts content for now)
    const typesContent = `/**
 * Definition of a property for a component
 */
export interface PropDef {
    /** The type of the property value */
    type: 'string' | 'number' | 'boolean' | 'ReactNode' | 'function';
    /** Whether the property is required */
    required: boolean;
    /** Optional default value for the property */
    defaultValue?: unknown;
}

/**
 * Represents a node in the generated component tree
 */
export interface ComponentNode {
    /** Unique identifier for the component */
    id: string;
    /** Human-readable name of the component */
    name: string;
    /** The structural role of the component */
    type: 'page' | 'layout' | 'section' | 'component' | 'atom';
    /** Brief description of what this component does */
    description: string;
    /** Map of property names to their definitions */
    props: Record<string, PropDef>;
    /** Nested child components */
    children: ComponentNode[];
    /** List of Tailwind CSS classes applied to this component */
    tailwindClasses: string[];
    /** External library dependencies required by this component */
    dependencies: string[];
    /** The generated source code for this component */
    code: string;
}
`;
    if (typesFolder) {
        typesFolder.file("index.ts", typesContent);
    }

    // Generate README
    const readmeContent = `# Generated UI Project

This project was generated by AgentUI from your PRD.

## Components

${components.map(c => `- **${c.name}** (${c.type}): ${c.description}
  - Props: ${Object.keys(c.props).length > 0 ? Object.keys(c.props).join(", ") : "None"}`).join("\n")}

## Usage

1. Copy the components into your project's \`components\` directory.
2. Ensure you have the following dependencies installed:
   - \`lucide-react\`
   - \`framer-motion\` (if animations enabled)
   - \`clsx\`, \`tailwind-merge\` (standard for shadcn-like components)
3. Configure your \`tailwind.config.js\` to include the paths to these components.
`;
    zip.file("README.md", readmeContent);

    // Generate and trigger download
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `agent-ui-export-${Date.now()}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
